// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import JsonLdSchema from "@/components/JsonLdSchema";
import WhatsAppButton from "@/components/WhatsAppButton";
import { client } from "@/lib/sanity.client";
import { groq } from "next-sanity";
import React from "react"; // Importamos React
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

const query = groq`{
  "businessProfile": *[_type == "perfilDeNegocio"][0],
  "navigation": *[_type == "navegacion"][0],
  "headerCarousel": *[_type == "headerCarousel"][0]{
    slides[]{
      _key,
      titulo,
      subtitulo,
      imagenPortada{
        asset->
      }
    }
  }
}`;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode; // Corregido a React.ReactNode
}) {
  let businessProfile = null;
  let navigation = null;
  let headerCarousel = null;
  
  try {
    const data = await client.fetch(query);
    businessProfile = data.businessProfile;
    navigation = data.navigation;
    headerCarousel = data.headerCarousel;
  } catch (error) {
    console.error('Error fetching layout data from Sanity:', error);
    // Continue with null values - components will handle gracefully
  }

  return (
    <html lang="es">
      <head>
        {businessProfile && <JsonLdSchema perfilDeNegocio={businessProfile} />}
      </head>
        <body className={`${inter.className}`}>
        {/* ESTA ES LA LÍNEA CRÍTICA CORREGIDA */}
        {businessProfile && <Header businessProfile={businessProfile} navigation={navigation} headerCarousel={headerCarousel} />}

        <main>{children}</main>

        <Footer />
        
        {/* WhatsApp Button - Siempre visible */}
        <WhatsAppButton />
        
        {/* Toaster para las notificaciones */}
        <Toaster 
          position="top-right"
          toastOptions={{
            duration: 4000,
            style: {
              background: '#1A1A1A',
              color: '#EAEAEA',
              border: '1px solid #8A2BE2',
            },
            success: {
              iconTheme: {
                primary: '#8A2BE2',
                secondary: '#EAEAEA',
              },
            },
            error: {
              iconTheme: {
                primary: '#ef4444',
                secondary: '#EAEAEA',
              },
            },
          }}
        />
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};