import type { Metadata } from "next";
import { inter } from '@/lib/fonts';
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import JsonLdSchema from "@/components/JsonLdSchema";
import WhatsAppButton from "@/components/WhatsAppButton";
import { client } from "@/lib/sanity.server";
import { groq } from "next-sanity";
import React from "react";
import { Toaster } from "react-hot-toast";


const query = groq`{
  "businessProfile": *[_type == "perfilDeNegocio"][0]
}`;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let businessProfile = null;
  
  try {
    const data = await client.fetch(query);
    businessProfile = data.businessProfile;
  } catch (error) {
    console.error('Error fetching layout data from Sanity:', error);
  }

  return (
    <html lang="es">
      <head>
        {businessProfile && <JsonLdSchema perfilDeNegocio={businessProfile} />}
      </head>
      <body className={`${inter.variable} font-sans`}>
        <Header />

        <main>{children}</main>

        <Footer />
        
        <WhatsAppButton />
        
        <Toaster 
          position="top-right"
          toastOptions={{
            duration: 4000,
            style: {
              background: '#1A1A1A',
              color: '#EAEAEA',
              border: '1px solid #30E0A0',
            },
            success: {
              iconTheme: {
                primary: '#30E0A0',
                secondary: '#EAEAEA',
              },
            },
            error: {
              iconTheme: {
                primary: '#ef4444',
                secondary: '#EAEAEA',
              },
            },
          }}
        />
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};