// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { client } from "@/lib/sanity.client";
import { groq } from "next-sanity";
import React from "react"; // Importamos React

const inter = Inter({ subsets: ["latin"] });

const query = groq`{
  "businessProfile": *[_type == "perfilDeNegocio"][0],
  "navigation": *[_type == "navegacion"][0]
}`;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode; // Corregido a React.ReactNode
}) {
  const { businessProfile, navigation } = await client.fetch(query);

  return (
    <html lang="es">
      <body className={inter.className}>
        {/* ESTA ES LA LÍNEA CRÍTICA CORREGIDA */}
        {businessProfile && <Header businessProfile={businessProfile} navigation={navigation} />}

        <main>{children}</main>

        {businessProfile && <Footer businessProfile={businessProfile} />}
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};